config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  
  namespace :admin do

    get 'login', to: 'sessions#new', as: 'login'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: 'logout'

    resources :articles, except: :show
    get 'articles/page/:page', to: 'articles#index', as: 'article_page'

    resources :galleries
    resources :categories, except: :show
    resources :slides

    resources :logs, param: :username, only: [:index, :show]
    resources :passwords, param: :username, only: :update
    resources :users

    # settings
    get 'settings', to: 'users#edit'

    patch 'edit_user', to: 'users#update'

    root 'dashboard#index'
  end

  resources :galleries, only: :index

  get 'articles/:page', to: 'articles#index', as: 'articles'

  get 'category/:category', to: 'categories#show', as: 'category'
  get ':slug', to: 'articles#show', as: 'article'

  root 'welcome#index'

end

app/models/slide.rb
class Slide < ActiveRecord::Base
  has_many :images, :as => :viewable
  validates :title, :url, presence: true

  def image_src(style)
    images.first.attachment.url(style)
  end
  
end

app/controllers/admin/slides_controller.rb
class Admin::SlidesController < ApplicationController
  before_action :authenticate_admin
  layout 'admin'
  
  def index
    @slides = Slide.includes(:images)
  end

  def new
    @slide = Slide.new
  end

  def create
    @slide = Slide.new(slide_params)
    if @slide.save
      @slide.images.create(attachment: params[:image])
      redirect_to admin_slides_path
    else
      render 'new'
    end
  end

  def edit
    @slide = Slide.find(params[:id])
  end

  def update
    @slide = Slide.find(params[:id])
    if @slide.update(slide_params)
      @slide.images.first.update(attachment: params[:image]) if params[:image]
      redirect_to admin_slides_path
    end
  end

  private
  def slide_params
    params.require(:slide).permit(:title, :url, :is_active)
  end
  
end

app/helpers/admin/slides_helper.rb
module Admin::SlidesHelper
end

app/views/admin/slides/edit.html.haml
= message @slide

.title.grid
  .col.mobile-10
    %h2 Lorem Ipsum is simply dummy text of the printing and typesetting industry
    %p Lorem Ipsum is simply dummy text of the printing and typesetting industry
  .col.mobile-2
    = link_to "Back", admin_slides_path, class: "btn icon-back"

.content
  = form_for [:admin, @slide], html: { multipart: true } do |f|
    .field
      = image_tag @slide.image_src(:thumb), class: "image-preview"
      = file_field_tag :image, id: "file", class: "image-upload"
      %label.icon-upload{ for: "file" } Upload photo
    .field
      %label Title
      = f.text_field :title
    .field
      %label Url
      = f.text_field :url
    .field
      = f.check_box :is_active
      %label{ for: "slide_is_active" } Active
    .field
      = f.button "Submit", class: "btn icon-check"

app/views/admin/slides/index.html.haml
.title.grid
  .col.mobile-10
    %h2 Slides
    %p Lorem Ipsum is simply dummy text of the printing and typesetting industry
  .col.mobile-2
    = link_to "New Slide", new_admin_slide_path, class: "btn icon-plus"

.content
  %table
    %thead
      %tr
        %th.p20 Image
        %th.p40 Title
        %th.p20 Active
        %th.p20 #
    %tbody
      - @slides.each do |slide|
        %tr
          %td.p20= image_tag slide.images.first.attachment.url(:thumb)
          %td.p40= link_to slide.title, edit_admin_slide_path(slide)
          %td.p20
            %span{ class: slide.is_active ? "slide-active" : "slide-deactive"}
          %td.p20
            = link_to "", edit_admin_slide_path(slide), class: "icon-edit"
            |
            = button_to admin_slide_path(slide), method: :delete, class: "icon-trash" do
              /

app/views/admin/slides/new.html.haml
= message @slide

.title.grid
  .col.mobile-10
    %h2 Lorem Ipsum is simply dummy text of the printing and typesetting industry
    %p Lorem Ipsum is simply dummy text of the printing and typesetting industry
  .col.mobile-2
    = link_to "Back", admin_slides_path, class: "btn icon-back"

.content
  = form_for [:admin, @slide], html: { multipart: true } do |f|
    .field
      = image_tag "golang.png", class: "image-preview"
      = file_field_tag :image, id: "file", class: "image-upload"
      %label.icon-upload{ for: "file" } Upload photo
    .field
      %label Title
      = f.text_field :title
    .field
      %label Url
      = f.text_field :url
    .field
      = f.check_box :is_active
      %label{ for: "slide_is_active" } Active
    .field
      = f.button "Submit", class: "btn icon-check"