config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  
  namespace :admin do

    get 'login', to: 'sessions#new', as: 'login'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: 'logout'

    resources :articles, except: :show
    get 'articles/page/:page', to: 'articles#index', as: 'article_page'

    resources :galleries
    resources :categories, except: :show
    resources :slides

    resources :logs, param: :username, only: [:index, :show]
    resources :passwords, param: :username, only: :update
    resources :users

    # settings
    get 'settings', to: 'users#edit'

    patch 'edit_user', to: 'users#update'

    root 'dashboard#index'
  end

  resources :galleries, only: :index

  get 'articles/:page', to: 'articles#index', as: 'articles'

  get 'category/:category', to: 'categories#show', as: 'category'
  get ':slug', to: 'articles#show', as: 'article'

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
  has_many :articles_tags
  has_many :tags, through: :articles_tags
  has_many :images, :as => :viewable

  attr_accessor :_tags
  after_save :save_article_tags

  validates :title, :slug, :summary, :content, :category_id, :_tags, presence: true

  def save_article_tags
    @tags = _tags.downcase.split(",")

    if self.tags.present? # edit article
      self.tags.each do |tag|
        self.articles_tags.find_by_tag_id(tag.id).destroy unless @tags.include? tag.name
      end
      @tags.each do |tag|
        self.tags << Tag.find_or_create(tag) unless self.tags.where(name: tag).present?
      end
    else # new article
      #@tags.each do |tag|
        #self.tags << Tag.find_or_create(tag)
      #end
      self.tags = @tags.map { |tag| Tag.find_or_create(tag) }
    end
  end

  def all_tags
    @tags = []
    tags.each{ |tag| @tags << tag.name }
    @tags
  end

  def self.paging(page)
    articles = order(created_at: :desc).includes(:category)
    total_article = articles.count
    per_page = 10
    total_page = total_article / per_page
    total_page = (total_article % per_page > 0) ? (total_page + 1) : total_page
    current_page = (page) ? page.to_i : 1
    {
      'data' => articles.limit(per_page).offset(per_page * (current_page - 1)),
      'total_page' => total_page,
      'current_page' => current_page
    }
  end

  def cat
    category
  end

  def time
    created_at.strftime("%d/%m%Y")
  end

  def image_src(style = :medium)
    images.first.attachment.url(style)
  end

  # Logs
  def article_log(action, current_admin)
    current_admin.logs.create(content: "<p><i class=\"#{action}\">#{action}</i> article | <a href=\"/#{self.slug}\" target=\"_blank\">#{self.title}</a></p>")
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :authenticate_admin
  layout 'admin'

  def index
    @articles = Article.paging(params[:page])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      @article.images.create(attachment: params[:images])
      @article.article_log('create', current_admin)
      redirect_to admin_articles_path
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
    @tags = @article.all_tags
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      @article.images.first.update(attachment: params[:images]) if params[:images]
      @article.article_log('update', current_admin)
      redirect_to admin_articles_path
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      @article.article_log('delete', current_admin)
      redirect_to admin_articles_path
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :slug, :summary, :content, :category_id, :_tags)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.limit(5).order(created_at: :desc).offset(5 * (params[:page].to_i - 1))
    @articles = @articles.present? ? @articles.as_json(methods: [:cat, :time, :image_src]) : nil
    respond_to do |format|
      format.json { render :json => @articles }
    end
  end

  def show
    @article = Article.find_by(:slug => params[:slug])
    @category = @article.category
    @related_news = Article.limit(10).order(created_at: :desc);
  end

end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/edit.html.haml
= message @article

.title.grid
  .col.mobile-10
    %h2 Lorem Ipsum is simply dummy text of the printing and typesetting industry
    %p Lorem Ipsum is simply dummy text of the printing and typesetting industry
  .col.mobile-2
    = link_to "Back", admin_articles_path, class: "btn icon-back"

.content
  = form_for [:admin, @article], html: { multipart: true } do |f|
    .grid
      .col.mobile-12
        .field
          = image_tag @article.image_src(:thumb), class: "image-preview"
          = file_field_tag :images, id: "file", class: "image-upload"
          %label{ for: "file", class: "icon-upload" } Upload photo
        .field
          %label Title
          = f.text_field :title, id: "name"
        .field
          %label Slug
          = f.text_field :slug, id: "slug"
        .field
          %label Summary
          = f.text_field :summary
        .field
          %label Category
          = f.select :category_id, Category.all.collect{ |c| [c.name, c.id] }, :include_blank => "Choose"
        .field
          %label Content
          = f.cktext_area :content, :ckeditor => { :toolbar => 'mini', :height => 350 }
        .field
          %label Tags (Press Enter for a new Tag)
          #chips
            = f.hidden_field :_tags, class: "chips-value", value: "#{@article.all_tags.join(",")}"
            .chips-show
              - @article.all_tags.each do |tag|
                %span.chip= tag
              %input{ type: "text", class: "chips-input" }
        .field
          = f.button "Submit", class: "btn icon-check"

app/views/admin/articles/index.html.haml
.title.grid
  .col.mobile-10
    %h2 Articles
    %p Lorem Ipsum is simply dummy text of the printing and typesetting industry
  .col.mobile-2
    = link_to "New Article", new_admin_article_path, class: "btn icon-plus"

.content
  %table
    %thead
      %tr
        %th.p40 Title
        %th.p20 Category
        %th.p20 Date
        %th.p20 #
    %tbody
      - @articles['data'].each do |article|
        %tr
          %td.p40= link_to article.title, edit_admin_article_path(article)
          %td.p20= article.category.name
          %td.p20= article.created_at.strftime('%d %B, %Y')
          %td.p20
            = link_to "", edit_admin_article_path(article), class: "icon-edit"
            |
            = button_to admin_article_path(article), method: :delete, class: "icon-trash" do
              /
  .pagination
    %ul
      %li.first-page= link_to "", admin_article_page_path(1), class: "icon-back"
      %li
        %ul.pages
          - @articles['total_page'].times do |page|
            %li= link_to page + 1, admin_article_page_path(page + 1), { class: ("active" if @articles['current_page'] == (page + 1)) }
      %li.last-page= link_to "", admin_article_page_path(@articles['total_page']), class: "icon-forward"

app/views/admin/articles/new.html.haml
= message @article

.title.grid
  .col.mobile-10
    %h2 Lorem Ipsum is simply dummy text of the printing and typesetting industry
    %p Lorem Ipsum is simply dummy text of the printing and typesetting industry
  .col.mobile-2
    = link_to "Back", admin_articles_path, class: "btn icon-back"

.content
  = form_for [:admin, @article], html: { multipart: true } do |f|
    .grid
      .col.mobile-12
        .field
          = image_tag "no-image.png", class: "image-preview"
          = file_field_tag :images, id: "file", class: "image-upload"
          %label{ for: "file", class: "icon-upload" } Upload photo
        .field
          %label Title
          = f.text_field :title, id: "name"
        .field
          %label Slug
          = f.text_field :slug, id: "slug"
        .field
          %label Summary
          = f.text_field :summary
        .field
          %label Category
          = f.select :category_id, Category.all.collect{ |c| [c.name, c.id] }, :include_blank => "Choose"
        .field
          %label Content
          = f.cktext_area :content, :ckeditor => { :toolbar => 'mini', :height => 350 }
        .field
          %label Tags (Press Enter for a new Tag)
          #chips
            = f.hidden_field :_tags, class: "chips-value"
            .chips-show
              %input{ type: "text", class: "chips-input" }
        .field
          = f.button "Submit", class: "btn icon-check"