config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  
  namespace :admin do

    get 'login', to: 'sessions#new', as: 'login'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: 'logout'

    resources :articles, except: :show
    get 'articles/page/:page', to: 'articles#index', as: 'article_page'

    resources :galleries
    resources :categories, except: :show
    resources :slides

    resources :logs, param: :username, only: [:index, :show]
    resources :passwords, param: :username, only: :update
    resources :users

    # settings
    get 'settings', to: 'users#edit'

    patch 'edit_user', to: 'users#update'

    root 'dashboard#index'
  end

  resources :galleries, only: :index

  get 'articles/:page', to: 'articles#index', as: 'articles'

  get 'category/:category', to: 'categories#show', as: 'category'
  get ':slug', to: 'articles#show', as: 'article'

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @slides = Slide.where(is_active: true)
    @articles = @hot_news = Article.limit(5).order(created_at: :desc).includes(:category, :images)
    @galleries = Gallery.order(created_at: :desc).limit(6)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.haml
<!--
========== SLIDE ========== --!>
#slide.hide-on-tablet-and-down
  - @slides.each do |slide|
    .slide
      = image_tag slide.images.first.attachment.url
      %h2= link_to slide.title, slide.url

<!--
========== MAIN ========== --!>
#main
  .container
    .grid
      .col.mobile-12.tablet-12.pc-8
        %h3.title.hide-on-tablet-and-down TIN MỚI
        #news
          - @articles.each do |article|
            / article
            .article.grid.card
              .col.mobile-4
                = link_to article_path(article.slug, format: "html") do
                  = image_tag article.image_src
              .col.mobile-8
                %h2= link_to article.title, article_path(article.slug, format: "html")
                .more
                  %span.icon-categories= link_to article.category.name, category_path(article.category.slug)
                  %span.icon-clock= article.created_at.strftime("%d/%m%Y")
                %p.hide-on-tablet-and-down= article.summary

      .col.mobile-12.tablet-12.pc-4.hide-on-tablet-and-down
        %h3.title TIN HOT
        #hot-news.card
          - @hot_news.each do |article|
            .article.grid
              .col.mobile-4
                = link_to article_path(article.slug, format: "html") do
                  = image_tag article.image_src(:thumb)
              .col.mobile-8
                %h2= link_to article.title, article_path(article.slug, format: "html")
        %h3.title THƯ VIỆN ẢNH
        #galleries.card
          - @galleries.each do |img|
            .image
              = image_tag img.attachment.url(:thumb)
          = link_to "Xem tất cả", galleries_path, class: "view-all"