config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  
  namespace :admin do

    get 'login', to: 'sessions#new', as: 'login'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: 'logout'

    resources :articles, except: :show
    get 'articles/page/:page', to: 'articles#index', as: 'article_page'

    resources :galleries
    resources :categories, except: :show
    resources :slides

    resources :logs, param: :username, only: [:index, :show]
    resources :passwords, param: :username, only: :update
    resources :users

    # settings
    get 'settings', to: 'users#edit'

    patch 'edit_user', to: 'users#update'

    root 'dashboard#index'
  end

  resources :galleries, only: :index

  get 'articles/:page', to: 'articles#index', as: 'articles'

  get 'category/:category', to: 'categories#show', as: 'category'
  get ':slug', to: 'articles#show', as: 'article'

  root 'welcome#index'

end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :admin
  belongs_to :article
end

app/controllers/admin/logs_controller.rb
class Admin::LogsController < ApplicationController
  before_action :authenticate_admin
  layout 'admin'
  
  def index
    if current_admin.is_admin?
      @logs = Log.order(created_at: :desc).includes(:admin)
    else
      @logs = current_admin.logs.order(created_at: :desc)
    end
  end

  def show
    @username = Admin.find_by(username: params[:username])
    @logs = @username.logs.order(created_at: :desc)
  end
end

app/helpers/admin/logs_helper.rb
module Admin::LogsHelper
end

app/views/admin/logs/index.html.haml
.title.grid
  .col.mobile-10
    %h2 Activity Log
    %p Lorem Ipsum is simply dummy text of the printing and typesetting industry
  .col.mobile-2
    /

.content
  - if @logs.present?
    %ul.logs
      - @logs.each do |log|
        %li
          .avatar
            = image_tag "no-avatar.jpg"
          %strong= link_to log.admin.username , admin_log_path(log.admin.username)
          = log.content.html_safe
          %span= log.created_at.strftime("%d %B, %Y - %H:%M")
  - else
    %i Nothing to show

app/views/admin/logs/show.html.haml
.title.grid
  .col.mobile-10
    %h2 Lorem Ipsum is simply dummy text of the printing and typesetting industry
    %p Lorem Ipsum is simply dummy text of the printing and typesetting industry
  .col.mobile-2
    = link_to "Back", admin_logs_path, class: "btn icon-back"

.content
  %ul.logs
    - @logs.each do |log|
      %li
        %p
          .avatar
            = image_tag "no-avatar.jpg"
          %strong= link_to log.admin.username , admin_log_path(log.admin.username)
          = log.content.html_safe
        %span= log.created_at.strftime("%d %B, %Y - %H:%M")